export const REGISTER_USER="REGISTER_USER"
export const LOGIN_USER="LOGIN_USER"
export const GET_AUTH_USER="GET_AUTH_USER"


export const LOGOUT_USER="LOGOUT_USER"
export const GET_CONFERANCE="GET_CONFERANCE"
export const GET_ARTICLE="GET_ARTICLE"
export const GET_ALL_USERS="GET_ALL_USERS"